### ISSUE TITLE
Jaxws-ri try to reach always http not https

### ISSUE THREAD

**Issue by BilgehanYildiz** [eclipse-ee4j/metro-jax-ws#100]
Hi I use openjdk and jaxws-maven-plugin to generate my wsdl.I can generate my wsdl and I want to use jaxwsri.My problem is in my wsdl there is a part with http:myservice in definition.I want to force it to https://myservice but when I check HttpURLConnection class it always try to reach http address.How can I force my call to https?

            QName qname2 = new QName("http://myschemas", "MyServiceImpl");
            MyServiceImpl service=new MyServiceImpl(new URL("https://myservice.svc?wsdl),qname2);
            Service service = MyServiceImpl .create(new URL("https://myservice.svc?wsdl), qname2);
            MyService reply=   service.getPort(MyService.class);
            MyResponse response=  reply.myRequest(request);

<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>jaxws-ri</artifactId>
    <version>2.3.2</version>
</dependency>

**Comment by lukasj** [comment]
sth like following should help:

```java
MyService reply =   service.getPort(MyService.class);
((BindingProvider) reply).getRequestContext()
    .put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "https://myservice.svc");
MyResponse response=  reply.myRequest(request);
```

**Comment by sikharis** [comment]
> sth like following should help:
> 
> ```java
> MyService reply =   service.getPort(MyService.class);
> ((BindingProvider) reply).getRequestContext()
>     .put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "https://myservice.svc");
> MyResponse response=  reply.myRequest(request);
> ```

you made my day sir, thanks
