### ISSUE TITLE
Missing change log for version 2.3.2-1/2.3.2.1

### ISSUE THREAD

**Issue by veita** [eclipse-ee4j/metro-jax-ws#104]
Our build process informed us about the new jax-ws version `2.3.2-1`.

However, there seems to be no change log, so it's unclear what kind of version `2.3.2-1` is. [Semantic versioning](https://semver.org/) suggests a pre-release version but this is only an educated guess.

Please give some information that can help us to decide if we need to upgrade or not.

**Comment by Archcry** [comment]
We would also like to know whether there are breaking changes in release 2.3.2-1 before we upgrade. Bumping this issue.

**Comment by lukasj** [comment]
github can show change log if one asks for [the diff](https://github.com/eclipse-ee4j/metro-jax-ws/compare/2.3.2...2.3.2-1) - from that it is clear that the only change was related to data handlers being used, important only if you're on JDK11
