### ISSUE TITLE
mark-generated should support the new Generated annotation from Java 9+

### ISSUE THREAD

**Issue by Vampire** [eclipse-ee4j/metro-jax-ws#134]
It would be nice if `mark-generated` would support choosing which generated annotation should be added to generated classes, the old one or the new one.

**Comment by lukasj** [comment]
By new do you mean `jakarta.annotation.Generated` or `javax.annotation.processing.Generated`? Assuming `javax.annotation.Generated` is the old one

**Comment by Vampire** [comment]
As `from Java 9+` would not match `jakarta.annotation.Generated` I indeed mean `javax.annotation.processing.Generated` and with old one `javax.annotation.Generated`, yes. :-)
Sorry for vague formulation.
