### ISSUE TITLE
jaxws-maven-plugin with xauthFile fails because of space in path

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/metro-jax-ws#162]
Using the following configuration fails when the project is located in a path containing a space.

```
<plugin>
	<groupId>com.sun.xml.ws</groupId>
	<artifactId>jaxws-maven-plugin</artifactId>
	<version>2.3.2</version>
	<executions>
		<execution>
			<goals>
				<goal>wsimport</goal>
			</goals>
			<configuration>
				<wsdlUrls>***</wsdlUrls>
				<xauthFile>WSDL_login.txt</xauthFile>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Maven information log indicates that the plugin tries to run: `jaxws:wsimport args: [-keep, -s, '<myProjectPath>/target/generated-sources/wsimport', -d, '<myProjectPath>/target/classes', -encoding, UTF-8, -Xnocompile, -Xauthfile, <myProjectPath>/WSDL_login.txt, "<myUrl>"]`. (I have redacted my project path and url.)

Note the lack of quotes to protect the argument to `-Xauthfile`. The command thus fails because it can’t locate the file.

**Comment by lukasj** [comment]
fixed by e9d3f48
