### ISSUE TITLE
WsImport.doMain() not closing binding file upon subsequent invocations

### ISSUE THREAD

**Issue by PhilSladen** [eclipse-ee4j/metro-jax-ws#215]
Calling WsImport.doMain(new String[] {"-keep", "-Xnocompile", "-p", "genTypesPkg", "-B-npa",
                  "-d", < path to temp dir>, "-b", < binding file>});

The first time it closes the binding file but upon subsequent invocations it appears to keep the binding file open because it is not possible to delete the file until the JVM is shutdown. Seems to happen with even the simplest WSDL. Binding file contents: < bindings xmlns=\"https://jakarta.ee/xml/ns/jaxws\">< enableWrapperStyle>false< /enableWrapperStyle>< /bindings>

**Comment by lukasj** [comment]
version, please

**Comment by PhilSladen** [comment]
3.0.0

**Comment by aserkes** [comment]
I cannot reproduce the problem. Any additional information (test/case) would be helpful.

**Comment by PhilSladen** [comment]
package issues;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.xml.sax.SAXParseException;

import com.sun.tools.ws.wscompile.WsimportTool;

public class Issue215 {
	private static final String TEMP_DIR_PREFIX = "slurpTmp";
	private static final String BINDING_FILE_PREFIX = "slurp";
	private static final String BINDING_FILE_POSTFIX = "bindingFile.xml";
	private static final String TYPES_PKG = "genTypesPkg";
	
	public static void main(String args[]) throws Exception {
		runWsImport();
		runWsImport();
		Thread.sleep(60000); // during this time, unable to delete the 2nd binding file
	}

	public static void runWsImport() throws Exception {
		Path tmpDir = null;
		File bindingFile = null;
		try {
			tmpDir = Files.createTempDirectory(TEMP_DIR_PREFIX);
			bindingFile = createBindingFile();
			new MyWsImportTool().run(new String[] {"-keep", "-Xnocompile", "-p", TYPES_PKG, "-B-npa",
					"-d", tmpDir.toAbsolutePath().toString(), "-extension", "-b",
					bindingFile.getAbsolutePath(), "simple.wsdl"});
			// Process the Java classes...
		} finally {
			if (tmpDir != null) {
				deleteDirectory(tmpDir.toFile(), true);
			}
			if (bindingFile != null) {
				// TODO: Currently fails on subsequent call to MyWsImportTool().run()
				// Work-around calls cleanUpBindingFiles() upon startup.
				System.out.println("bindingFile=" + bindingFile.getAbsolutePath() + ", delete()=" + bindingFile.delete());
			}
		}
	}

	// Local version of WsimportTool so that it logs directly to our logger.
	//
	private static class MyWsImportTool extends WsimportTool {
		public MyWsImportTool() {
			super(System.out);
		}

		public boolean run(String[] args) {
			ImportListener listener = new ImportListener();
			Receiver receiver = new Receiver(listener);
			return super.run(args, listener, receiver);
		}

		private class ImportListener extends Listener {
			@Override
			public void message(String msg) {}
			@Override
			public void error(SAXParseException exception) {
				System.out.println(exception.getMessage());
			}
			@Override
			public void fatalError(SAXParseException exception) {
				System.out.println(exception.getMessage());
			}
			@Override
			public void warning(SAXParseException exception) {
				System.out.println(exception.getMessage());
			}
			@Override
			public void debug(SAXParseException exception) {
				System.out.println(exception.getMessage());
			}
			@Override
			public void info(SAXParseException exception) {
				System.out.println(exception.getMessage());
			}
		}
	}

	private static File createBindingFile() throws IOException {
		String bindingXml = "<bindings xmlns=\"https://jakarta.ee/xml/ns/jaxws\"><enableWrapperStyle>false</enableWrapperStyle></bindings>";
		File bindingFile = File.createTempFile(BINDING_FILE_PREFIX, BINDING_FILE_POSTFIX);
		FileWriter out = new FileWriter(bindingFile);
		out.write(bindingXml);
		out.close();
		return bindingFile;
	}
    
    private static boolean deleteDirectory(File dir, boolean log) {
    	for (File file : dir.listFiles()) {
    		if (file.isDirectory()) {
    			deleteDirectory(file, log);
    		} else if (!file.delete()) {
    			if (log) {
    				System.out.println("Failed to delete " + file);
    			}
    		}
    	}
    	boolean success;
    	if (!(success=dir.delete())) {
    		if (log) {
    			System.out.println("Failed to delete " + dir);
    		}
		}
    	return success;
    }
}

**Comment by lukasj** [comment]
Operating systems do differ in file locking, so I assume this is on Windows. Can you confirm?

**Comment by PhilSladen** [comment]
Windows 10 Home, 64 bit, OS build 19042.928. Here is the simple.wsdl referred to in the reproduction code:

<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://slurp.com/io" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="SlurpServices" targetNamespace="http://slurp.com/io">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://slurp.com/io" version="1.0">
			<element name="Adder">
				<complexType>
					<sequence>
						<element name="Int1" type="long" />
						<element name="Int2" type="long" />
					</sequence>
				</complexType>
			</element>
			<element name="AdderResponse">
				<complexType>
					<sequence>
						<element name="Sum" type="long" />
					</sequence>
				</complexType>
			</element>
		</schema>
	</wsdl:types>
	<wsdl:message name="Adder">
		<wsdl:part element="tns:Adder" name="parameters" />
	</wsdl:message>
	<wsdl:message name="AdderResponse">
		<wsdl:part element="tns:AdderResponse" name="parameters" />
	</wsdl:message>
	<wsdl:portType name="SlurpServices">
		<wsdl:operation name="Adder">
			<wsdl:input message="tns:Adder" name="Adder" />
			<wsdl:output message="tns:AdderResponse" name="AdderResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SlurpServicesBinding" type="tns:SlurpServices">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="Adder">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="Adder">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="AdderResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SlurpServices">
		<wsdl:port binding="tns:SlurpServicesBinding" name="SlurpServicesImplPort">
			<soap:address location="http://localhost:8080/soap" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>

**Comment by PhilSladen** [comment]
[simple.wsdl.txt](https://github.com/eclipse-ee4j/metro-jax-ws/files/6367090/simple.wsdl.txt)

**Comment by lukasj** [comment]
can you try 3.0.2-SNAPSHOT and let me know if the issue is gone, please?

**Comment by aserkes** [comment]
The issue is gone.

**Comment by PhilSladen** [comment]
Hi Lukas,
I would like to check the fix. Is there a link to built binaries for 3.0.2-SNAPSHOT?
Thanks,Phil
    On Friday, 4 June 2021, 13:11:56 BST, Lukas Jungmann ***@***.***> wrote:  
 
 


can you try 3.0.2-SNAPSHOT and let me know if the issue is gone, please?

**Comment by lukasj** [comment]
[3.0.2-SNAPSHOT.zip](https://jakarta.oss.sonatype.org/service/local/repositories/snapshots/content/com/sun/xml/ws/jaxws-ri/3.0.2-SNAPSHOT/jaxws-ri-3.0.2-20210606.172555-10.zip) - under jakarta namespace
[2.3.5-SNAPSHOT.zip](https://jakarta.oss.sonatype.org/service/local/repositories/snapshots/content/com/sun/xml/ws/jaxws-ri/2.3.5-SNAPSHOT/jaxws-ri-2.3.5-20210607.164137-2.zip) - under javax namespace

or use https://jakarta.oss.sonatype.org/content/repositories/snapshots repo as shown ie at https://eclipse-ee4j.github.io/mail/#Development_Releases

**Comment by PhilSladen** [comment]
I tested with jars from the 3.0.2-SNAPSHOT link just provided and the issue appears to have been fixed. Many thanks.

**Comment by lukasj** [comment]
great, thanks for checking!
