### ISSUE TITLE
Unable to resolve dependencies for release 2.3.4: org.glassfish.gmbal:gmbal-api-only:jar:4.0.3

### ISSUE THREAD

**Issue by asbachb** [eclipse-ee4j/metro-jax-ws#216]
Seems that release `2.3.4` references a dependency which is not publicly  available:

https://mvnrepository.com/artifact/org.glassfish.gmbal/gmbal-api-only

Latest release is `org.glassfish.gmbal:gmbal-api-only:jar:4.0.2`.

**Comment by lukasj** [comment]
one can use staging repo for now. The definition is ie [here](https://wiki.eclipse.org/EclipseLink/Maven#Sample_pom.xml_.28Staging.29)

**Comment by asbachb** [comment]
@lukasj Do you know if there's any ETA for pushing the artifact to public repos? I'm on a business environment where it is quite hard to add any additional sources for maven artifacts.

**Comment by lukasj** [comment]
No, I have no control there. @arjantijms or @smillidge can one of you push gmbal (api, etc) to central, please?

**Comment by smillidge** [comment]
OK it has been promoted. I must have missed this one when I released the latest Corba. It may take some hours to propogate to maven central.

**Comment by lukasj** [comment]
thanks @smillidge !

**Comment by asbachb** [comment]
thanks @lukasj and @smillidge for quickly solving that issue!
