### ISSUE TITLE
JAXB WARNING: Illegal reflective access by org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector

### ISSUE THREAD

**Issue by PhilSladen** [eclipse-ee4j/metro-jax-ws#218]
I get this warning when using 3.0.0 jars and testing with openjdk-14+36_windows-x64_bin. Searches seem to imply that this warning was removed in version 2.3.1 but seems to be back again.

**Comment by lukasj** [comment]
see https://github.com/eclipse-ee4j/jaxb-ri/issues/1501#issuecomment-767555720

**Comment by PhilSladen** [comment]
Many thanks. "Multi-Release: true" in the manifest also removed warnings for me.
