### ISSUE TITLE
WEBSERVICE CALL CAN FAIL IF PAYLOAD INCLUDES WSSE:SECURITY HEADER 

### ISSUE THREAD

**Issue by monicadragomir** [eclipse-ee4j/metro-jax-ws#3]
1. A WebLogic server is running with a Java Security Manager
2. A webservice exists with no OWSM policy attached
3. A web service call is made with a wsse:security element in the header (the
element can be empty).

Then the call fails with:

javax.xml.soap.SOAPException: java.lang.UnsupportedOperationException:
javax.xml.transform.TransformerConfigurationException:
FEATURE_SECURE_PROCESSING: Cannot set the feature to false when security
manager is present.

**Comment by lukasj** [comment]
closed by #94

**Comment by tjololo** [comment]
Is the fix that closed this issue available somewhere?
