### ISSUE TITLE
Can't include jaxws-rt 2.2.10 using gradle

### ISSUE THREAD

**Issue by niclarcipretti** [eclipse-ee4j/metro-jax-ws#30]
I'm having some trouble importing jaxws-rt with gradle. Appearently, jaxws-rt has an internal dependency with glassfish's ha-api:3.1.9, and this one should have a hk2-jar file that does not exists (even in Maven's central repository). The error I get is:

```
Execution` failed for task ':compileJava'.
> Could not resolve all dependencies for configuration ':detachedConfiguration1'.
   > Could not determine artifacts for org.glassfish.ha:ha-api:3.1.9
      > Could not get resource 'http://myartifactory.com/org/glassfish/ha/ha-api/3.1.9/ha-api-3.1.9.hk2-jar'.
         > Could not HEAD 'http://myartifactory.com/org/glassfish/ha/ha-api/3.1.9/ha-api-3.1.9.hk2-jar'. 
```

Can someone give me a hand with this? The only workaround I found was to exclude ha-api from jaxws-rt dependency (not properly tested for side effects).

Cheers

Nikao

**Comment by borjafg** [comment]
Glassfish's ha-api version 3.1.9 has a dependency with "hk2" version 1.6.14

You can find the hk2 jar here => [https://mvnrepository.com/artifact/org.glassfish.hk2/hk2/1.6.14](url)

**Comment by niclarcipretti** [comment]
Hi borjafg. I'm aware of this. But that's not a viable solution for me. The dependency should work by it self.
Thanks anyway.

**Comment by borjafg** [comment]
What version of jax-ws are you using? I think is "2.3.1". If that is the case, you should try to use the 2.3.2 version.

**Comment by lukasj** [comment]
I can see hk2:1.6.14 in mvn central: https://repo1.maven.org/maven2/org/glassfish/hk2/hk2/1.6.14/
