### ISSUE TITLE
MANY PROXY CLASS CREATED WHILE CREATING WEB SERVICE CLIENT ON WLS 12213 

### ISSUE THREAD

**Issue by monicadragomir** [eclipse-ee4j/metro-jax-ws#32]
The proxy class is created for a "delegating loader", that can load classes from both the web service interface loader as well as from the JAXWS loader. Each time a proxy is needed, a "delegating loader" is instantiated, hence the proxy class is never reused.

If there is already a parent child relationship between the web service interface class loader and the JAXWS loader, do not create a delegating loader, use the web service interface class loader further.

**Comment by lukasj** [comment]
fixed by #33
