### ISSUE TITLE
SaajStaxWriter might not add the namespace declarations to the correct element

### ISSUE THREAD

**Issue by mbali** [eclipse-ee4j/metro-jax-ws#39]
While creating a new `SOAPElement` based on the deferred element in  `DeferredElement.flushTo`, the namespace declarations are added to the parent element instead of the newly created element.
The line with the problem in current master: [com.sun.xml.ws.api.message.saaj.SaajStaxWriter:487](https://github.com/eclipse-ee4j/metro-jax-ws/blob/16810e6f6a3dad5c4c4ef08fd76130a68dc08fea/jaxws-ri/rt/src/main/java/com/sun/xml/ws/api/message/saaj/SaajStaxWriter.java#L487)
This bug looks like a duplicate of  [JDK-8186441](https://bugs.openjdk.java.net/browse/JDK-8186441)

**Comment by lukasj** [comment]
looks like fixed in recent versions.
