### ISSUE TITLE
Any plan to address below issues

### ISSUE THREAD

**Issue by rarathore** [eclipse-ee4j/metro-jax-ws#40]
Hi Team,

Please let us know if you have any plan to fix below issues in metro jax ws jar

https://github.com/javaee/metro-jax-ws/issues/1122 
https://github.com/javaee/metro-jax-ws/issues/868 
https://github.com/javaee/metro-jax-ws/issues/1184

**Comment by lukasj** [comment]
these should have been fixed by #36
