### ISSUE TITLE
Website / Documentation for Maven plugin

### ISSUE THREAD

**Issue by twiedow** [eclipse-ee4j/metro-jax-ws#41]
I just ran into some confusions regarding the official Maven plugin for JAX-WS.

When I started looking for the JAX-WS plugin (org.codehaus.mojo:jaxws-maven-plugin) I was directed to MojoHaus (http://www.mojohaus.org/jaxws-maven-plugin).
Because I was wondering why the latest version of this plugin is almost 2 years old and only supporting Java 1.6, I had a look on maven.org to check if the version information was up-to-date.

When I searched for jaxws-maven-plugin on the Maven repository I also found a plugin with groupId com.sun.xml.ws with the latest version 2.3.2 from January 2019. The problem is that I could not find any documentation about this plugin on the web. The official home of the JAX-WS tools only refer to the Github page with no further documentation.

So I asked Lukas Jungmann since he is listed as developer in the POM.
He told me that this plugin is the way to go and that it also supports Java 11. For documentation I can use the MojoHaus docs since there was no big change.

I would be great to fix the information on MojoHaus or add some information on the JAX-WS project home which Maven plugin is the one to use. If there are changes regarding the API of the plugin it would also be great to update the information.

**Comment by lukasj** [comment]
docs has been updated, see https://eclipse-ee4j.github.io/metro-jax-ws/jaxws-maven-plugin/
