### ISSUE TITLE
Consider following Maven and OSGi packaging, naming, and versioning rules defined by GF

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-jax-ws#505]
see: [https://wikis.oracle.com/display/GlassFish/Maven+Versioning+Rules](https://wikis.oracle.com/display/GlassFish/Maven+Versioning+Rules)
#### Affected Versions
[2.2.7]

Source: [https://github.com/javaee/metro-jax-ws/issues/1081](https://github.com/javaee/metro-jax-ws/issues/1081)
Author: glassfishrobot

**Comment by lukasj** [comment]
this is obsolete
