### ISSUE TITLE
Where to find documentation?

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-jax-ws#580]
Hi,

I'm trying to find documentation for jax-ws, preferably in JavaDocs format. 
The issue I'm having is that the documentation link I've been given (http://jax-ws.java.net/nonav/jaxws-api/2.2/index.html) just redirects to the main page of this github repo.

I've noticed that there are some DocBook formatted files in jaxws-ri/docs. Are these useful and should I attempt to convert them to a readable format?

Thanks

Source: [https://github.com/javaee/metro-jax-ws/issues/1199](https://github.com/javaee/metro-jax-ws/issues/1199)
Author: benjamingorman

**Comment by lukasj** [comment]
see https://eclipse-ee4j.github.io/metro-jax-ws/
