### ISSUE TITLE
SpotBugs(FindBugs) should be run against JAX-WS

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-jax-ws#605]
Any issues should be addressed that are still outstanding

Source: [https://github.com/javaee/metro-jax-ws/issues/1231](https://github.com/javaee/metro-jax-ws/issues/1231)
Author: LanceAndersen

**Comment by lukasj** [comment]
done in https://ci.eclipse.org/metro/job/jax-ws-master-build/
