### ISSUE TITLE
It looks the ProviderImpl has been moved to pacakge "com\sun\xml\ws\spi" from "com.sun.xml.internal.ws.spi", but the Provider class is still referring in the old package?

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-jax-ws#609]
Source: [https://github.com/javaee/metro-jax-ws/issues/1247](https://github.com/javaee/metro-jax-ws/issues/1247)
Author: FuminZhou

**Comment by lukasj** [comment]
fixed already

**Comment by lowrider59** [comment]
> fixed already

Fixed how?

I still get this issue in JDK-17.
