### ISSUE TITLE
Fix for bug 28773106

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-jax-ws#610]
Here the issue is that The @XmlElement(nillable=false) doesn't work with String[]
i.e. nillable attribute is not honored by any array elements

So for the fix I have removed the check nav.isArray(type) from AbstractWrapperBeanGenerator.processXmlElement which sets nillable to true for all array type elements

Signed-off-by: vavishal vaibhav.vishal@oracle.com

Source: [https://github.com/javaee/metro-jax-ws/pull/1254](https://github.com/javaee/metro-jax-ws/pull/1254)
Author: vavishal

**Comment by lukasj** [comment]
handled by `com.sun.xml.ws.jaxb.allowNonNillableArray=true|false` property
