### ISSUE TITLE
SOAP with HelidonMP appends '/metro' to the endpoint url.

### ISSUE THREAD

**Issue by vipinjnair** [eclipse-ee4j/metro-jax-ws#626]
Hi,

By following the instructions at 
https://medium.com/helidon/soap-with-helidon-51bb2dc3189e
I implemented a sample SOAP service using the 'org.glassfish.metro:helidon-mp' dependency. 

The SOAP endpoint works but it appends a "/metro" to the end point url. This is not an issue with helidon-se dependency. 

Raising this issue to remove the hardcoded '/metro' from the endpoint url. 

Here is the code block where this gets appended 

+++++++++++++++++++++++++++
[https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/extras/helidon-i[…]c/main/java/org/eclipse/metro/helidon/mp/MetroCdiExtension.java](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/extras/helidon-integration/mp/src/main/java/org/eclipse/metro/helidon/mp/MetroCdiExtension.java)

```
public class MetroCdiExtension implements Extension {

    public void start(@Observes @Priority(Interceptor.Priority.PLATFORM_AFTER) @Initialized(ApplicationScoped.class) Object event, BeanManager bm) {
        org.eclipse.microprofile.config.Config config = ConfigProvider.getConfig();
        Config helidonConfig = MpConfig.toHelidonConfig(config).get("metro");
        MetroSupport metro = MetroSupport.create(helidonConfig);
        RoutingBuilders.create(helidonConfig)
                .routingBuilder()
                .register("/metro", metro);
    }

}
```

+++++++++++++++++++++++++++

**Comment by lukasj** [comment]
this is fixed in the version for helidon3 (currently lives @ https://github.com/lukasj/helidon-soap-ws)
