### ISSUE TITLE
Problem with spring boot migration 3.1.4

### ISSUE THREAD

**Issue by yasin-herken** [eclipse-ee4j/metro-jax-ws#675]
I am trying to migrate my spring boot application from 2.7.0 to 3.1.4. 
`<dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>4.0.0</version>
    </dependency>`
I tried 4.0.0 but it generates still javax.

**Comment by yasin-herken** [comment]
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
It generates that. it imports 
`import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;`
But I need to convert it to the import jakarta
I am trying to figure out it.

**Comment by yasin-herken** [comment]
I can't remember what I did at that time but I figured out it, I guess I did upgrading spring cloud and it solved the problem

**Comment by yasin-herken** [comment]
I changed my 

> <groupId>org.codehaus.mojo</groupId>
<artifactId>jaxws-maven-plugin</artifactId>
to the 
> <groupId>org.apache.cxf</groupId>
    <artifactId>cxf-codegen-plugin</artifactId>

**Comment by laurentschoelens** [comment]
Thanks for the quick answer.
The mojo plugin is now part of this repository with the new coordinates mentionned above `com.sun.xml.ws:jaxws-maven-plugin`

**Comment by laurentschoelens** [comment]
If you don't have this issue anymore, I'd suggest you to close it 😄

**Comment by yasin-herken** [comment]
> If you don't have this issue anymore, I'd suggest you to close it 😄

:)
