### ISSUE TITLE
metro-jax-ws is incompatible with Java 11 due to usage of JDK removed internal API by XmlCatalogUtil.java

### ISSUE THREAD

**Issue by rohitgaikwad09** [eclipse-ee4j/metro-jax-ws#86]
The [XmlCatalogUtil.java](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/util/xml/XmlCatalogUtil.java) class makes use of 3 JDK-11 **removed** internal APIs as below:

**1)** com.sun.org.apache.xml.internal.resolver.**Catalog**;
**2)** com.sun.org.apache.xml.internal.resolver.**CatalogManager**;
**3)** com.sun.org.apache.xml.internal.resolver.tools.**CatalogResolver**;

Below is the jdeps scan report on JDK-11.0.5
{
   "com.sun.xml.ws.util.xml.XmlCatalogUtil$1"         -> "com.sun.org.apache.xml.internal.resolver.**Catalog** (JDK internal API (J**DK removed internal API**))";
   "com.sun.xml.ws.util.xml.XmlCatalogUtil$1"         -> "com.sun.org.apache.xml.internal.resolver.**CatalogManager** (**JDK internal API (JDK removed internal API**))";
   "com.sun.xml.ws.util.xml.XmlCatalogUtil$1"         -> "com.sun.org.apache.xml.internal.resolver.tools.**CatalogResolver** (**JDK internal API (JDK removed internal API**))";
}

The above reference usages to removed APIs makes metro-jax-ws incompatible with Java/JDK 11. Can someone please have a look into this issue?

**Comment by rohitgaikwad09** [comment]
I see an [XmlCatalogUtil.java](https://github.com/eclipse-ee4j/metro-jax-ws/tree/master/jaxws-ri/runtime/rt/src/main/java-mr/9/com/sun/xml/ws/util/xml) file at java-mr location. I think its created for Java 9+. Is the java-mr patch getting bundled into a jar file like [JAX WS RI Runtime Bundle](https://mvnrepository.com/artifact/com.sun.xml.ws/jaxws-rt/2.3.2) on maven site? We need a jar file which contains this patch, is there any download location for this?

**Comment by lukasj** [comment]
jaxws-rt.jar, even in 2.3.2 version, contains correct XmlCatalogUtil class under META-INF/versions/9. If this is not being picked up at the runtime, then it is very likely problem on the environment - ie if ant tasks are used, then either Ant 1.10.7+ is required, or as a workaround `-Djdk.util.jar.enableMultiRelease=force` must be passed to the Ant command line

**Comment by rohitgaikwad09** [comment]
Thanks Lukas for quick response, I have not yet used the jaxws-rt.jar 2.3.2 with JDK 11, I did static scans on this jar using jdeps. If there are any issues at runtime will have a look into it.
