### ISSUE TITLE
metro-jax-ws uses woodstox-core (version 5.1.0) which uses JDK-11 removed internal APIs

### ISSUE THREAD

**Issue by rohitgaikwad09** [eclipse-ee4j/metro-jax-ws#87]
- A dependency library woodstox-core.jar version 5.1.0 of metro-jax-ws uses below JDK-11 removed internal API

digraph "woodstox-core.jar" {
   "com.ctc.wstx.msv.GenericMsvValidator"  -> "org.relaxng.datatype.**Datatype** (**JDK internal API (JDK removed internal API))**";
}

- The latest version of woodstox-core.jar 6.0.2 uses below JDK-11 removed internal APIs:

digraph "woodstox-core-6.0.2.jar" {
   "com.ctc.wstx.shaded.msv_core.driver.textui.Driver" -> "com.sun.org.apache.xml.internal.resolver.Catalog (JDK internal API (**JDK removed internal API**))";
   "com.ctc.wstx.shaded.msv_core.driver.textui.Driver" -> "com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver (JDK internal API (**JDK removed internal API**))";
}

- Can someone please have a look into this issue? What are its impacts of it on metro-jax-ws's compatibility with Java/JDK-11?

**Comment by lukasj** [comment]
msv is not used anymore, so these are not relevant. File a new issue for the exact problem at runtime/tooltime with clear use-case

**Comment by mads1980** [comment]
Adding resolver-20050927.jar to the classpath fixes the issue with woodstock-core if anyone is interested.
