### ISSUE TITLE
Memory leak on ThreadLocalContainerResolver

### ISSUE THREAD

**Issue by DrZ7** [eclipse-ee4j/metro-jax-ws#98]
com.sun.xml.ws.api.server.ThreadLocalContainerResolver.containerThreadLocal creates a memory leak:

>  SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [xxxx] created a ThreadLocal with key of type [com.sun.xml.ws.api.server.ThreadLocalContainerResolver$1] (value [com.sun.xml.ws.api.server.ThreadLocalContainerResolver$1@5709e10b]) and a value of type [com.sun.xml.ws.api.server.Container.NoneContainer] (value [com.sun.xml.ws.api.server.Container$NoneContainer@114badf0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

initValue is triggered by com.sun.xml.ws.util.ServiceFinder.find(Class<T>, ClassLoader)

https://github.com/javaee/metro-jax-ws/issues/1145

**Comment by DrZ7** [comment]
A remove on com.sun.xml.ws.api.server.ThreadLocalContainerResolver.containerThreadLocal does not stop the leak.
Only fix is to remove the initialValue Container.NONE.

**Comment by tech-consortium** [comment]
@DrZ7 Can you please explain what you mean by "Only fix is to remove the initialValue Container.NONE."

**Comment by DrZ7** [comment]
fix might have been the wrong word, workaround that worked for us to prevent the leak:

use:
`//no initial value, which leads to a memory lead
  private final ThreadLocal<Container> containerThreadLocal = new ThreadLocal<Container>();`
  
  instead of:
  `private ThreadLocal<Container> containerThreadLocal = new ThreadLocal<Container>() {
        @Override
        protected Container initialValue() {
            return Container.NONE;
        }
    };`

**Comment by tech-consortium** [comment]
This leak has haunted us for years, is this going to be backported to 3.x?

**Comment by Unlogic-dot-se** [comment]
> This leak has haunted us for years, is this going to be backported to 3.x?

That is a very good point, this bug should have been fixed long ago.
